Replace old filter_properties with new RequestSpec NovaObject
The host_passes() method in blazar_filter depends on an old
filter_properties dictionary. However, Nova replaced it by a new
RequestSpec NovaObject. Therefore, the filter is throwing this error:

    "TypeError: 'RequestSpec' object has no attribute '__getitem__'."

This commit changes host_passes() to use the new RequestSpec NovaObject.

Change-Id: I0e57f4ee4655a8658419bfaaffad524369ee10b9
Closes-Bug: #1642137